version: '3.8'
services:
  postgres:
    image: postgres
    restart: always
    env_file:
      - ./.env
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  server:
    build: ./
    container_name: server_container
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.env
  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
    expose:
      - 6379
    volumes:
      - redisData:/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  pgdata:
  redisData: